<?php
$form = $this->form;
$fieldset = $form->get('post');

$title = $fieldset->get('title');
$title->setAttribute('class', 'form-control');
$title->setAttribute('placeholder', 'Post title');

$text = $fieldset->get('text');
$text->setAttribute('class', 'form-control');
$text->setAttribute('placeholder', 'Post content');

$submit = $form->get('submit');
$submit->setValue($this->submitLabel);
$submit->setAttribute('class', 'btn btn-primary');

$form->prepare();

echo $this->form()->openTag($form);
?>

    <fieldset>
        <div class="panel panel-default">
             <div class="panel-heading">
                <div class="form-group">
                    <?= $this->formLabel($title) ?>
                    <?= $this->formElement($title) ?>
                    <?= $this->formElementErrors()->render($title, ['class' => 'help-block']) ?>
                </div>
            </div>
            <div class="panel-body">
                <div class="form-group">
                    <?= $this->formLabel($text) ?>
                    <?= $this->formElement($text) ?>
                    <?= $this->formElementErrors()->render($text, ['class' => 'help-block']) ?>
                </div>
            </div>

        </div>
    </fieldset>

<?php
echo $this->formSubmit($submit);
?>
    <a class="btn btn-danger" href="<?= $this->url('blog/detail', [], true) ?>">Cancel changes</a>
<?php

echo $this->formHidden($fieldset->get('id'));
echo $this->form()->closeTag();