<h1>Post Details</h1>

<div class="btn-group" role="group" aria-label="Return to blogs">
    <a class="btn btn-xs btn-primary" href="<?= $this->url('blog') ?>">Return to blogs</a>
</div>
<br>
<br>

<div class="panel panel-default">
    <div class="panel-heading">

        <h3><?= $this->escapeHtml($this->post->getTitle()) ?></h3>
        <div class="btn-group" role="group" aria-label="Post actions">
            <a class="btn btn-xs btn-default" href="<?= $this->url('blog/edit', ['id' => $post->getId()]) ?>">Edit</a>
            <a class="btn btn-xs btn-danger" href="<?= $this->url('blog/delete', ['id' => $post->getId()]) ?>">Delete</a>
        </div>
    </div>
    <div class="panel-body">
        <?= $this->escapeHtml($this->post->getText()) ?>
    </div>
</div>

